language: java

jdk:
  - oraclejdk8

before_install:
  - sudo apt-get update -yqq
  - sudo apt-get install -yqq python3 python3-pip

install:
  - pip install pre-commit

script:
  - pre-commit run --allow-unstaged-config --all-files --verbose
  - mvn -f elucidate-parent/pom.xml clean package install -U -B
  - mvn -f elucidate-common-lib/pom.xml clean test package install -U -B
  - mvn -f elucidate-converter/pom.xml clean test package install -U -B
  - mvn -f elucidate-server/pom.xml clean test package install -U -B
