language: java

jdk:
  - oraclejdk8

before_install:
  - sudo apt-get update -yqq
  - sudo apt-get install python3 python3-pip

install:
  - pip install pre-commit

script:
  - pre-commit run --allow-unstaged-config --all-files --verbose
  - mvn clean test -B
